### PR TITLE
Devin's search but with some minor tweaks

### PR DESCRIPTION
**Pull request by Flaque**
# Overview

See #62

### CODE REVIEW

**Comment by Flaque** [comment]
Hmm. I think I might close this for now actually. Sorry for the bait and switch here, I know I asked you to do this! 🙏

I've been using a version with this on it for a week or so and never found myself using it. 

I think the main use case of Quirk is to record thoughts, not really to search through thoughts. So until this is something that people are strongly pulling for this, I'm going to hesitate to add it.

**Comment by devinroche** [comment]
No worries, I agree with closing this actually. I feel like a search only gets in the way of viewing the list!

**Comment by Flaque** [comment]
❤️ I think the password protect is probably the most requested thing to work on at the moment; it's hugely asked for and provides a fair amount of value for people.

**Comment by devinroche** [comment]
yeah that would actually be super cool ill look into that!

**Pull request closed without merging**
