### PR TITLE
Adds test coverage over localization keys

### PR DESCRIPTION
**Pull request by briankung**
This recursively matches the keys against the english localization keys. Throwing up a PR to get feedback. Also do we want to have the tests fail or just issue warnings?

### CODE REVIEW

**Comment by briankung** [comment]
Woops, I meant to make this a draft pull request. Oh well.

**Comment by briankung** [comment]
My questions are:

- Should the tests fail if, say, German has _more_ localization keys than English?
    - If the tests should not fail in that case, then what should happen?
- If the keys are missing, should the tests (and therefore the test suite) what should happen? Having failing tests sitting around just seems anathema, but I haven't been able to find anything about allowing tests to pass with just a warning.

**Comment by devinroche** [comment]
This is super cool @briankung thanks for doing this! I left some comments below. I'm totally fine discussing them if you want too!

* Should the tests fail if, say, German has more localization keys than English? I've opted to let these pass with the toMatchObject matcher

I think we should fail if German (example) has more keys than English. If we are using English as our fallback language we will most likely need it to be the most up-to-date version.

* If the keys are missing, should the tests (and therefore the test suite) what should happen? Having failing tests sitting around just seems anathema, but I haven't been able to find anything about allowing tests to pass with just a warning.

I think @Flaque is working on CI stuff next so that if there is failing tests they cant be merged. I like the idea of having it pass but show a warning, but cant find anything on that on jests site either 😢.

**Comment by briankung** [comment]
> I think we should fail if German (example) has more keys than English. If we are using English as our fallback language we will most likely need it to be the most up-to-date version.

I think in the case of the German translations, the emphasis falls in a different place in the sentence. How should we handle that? I read [on another issue](https://github.com/Flaque/quirk/issues/36#issuecomment-468902745) that it's possible to add rich text _within_ the localization string itself instead of outside it. Is that a possibility? That way we don't have to break out the German into a separate line:

German:
```json
"thoughts_arent_thoughts": {
  "line1": "Zweitens: deine Gedanken können",
  "emphasis1": "unbewusst angelernt",
  "line2": "sein"
}
```

English:
```json
"thoughts_arent_thoughts": {
  "line1": "Second: your thoughts can be",
  "emphasis1": "automatic."
},
```

As an aside, it appears that the German translations are at least not displaying `line2`.

**Comment by devinroche** [comment]
Ahh sorry i misunderstood what you were saying by that! Thats a really good point. Lets leave it how you set up then since you are on the right track accounting for that.

**Comment by briankung** [comment]
I'll leave it, though it did raise an issue - what should be done about `thoughts_arent_thoughts.line2`? It looks like it is just not being used. I'll bring it up on the original German PR.

**Comment by Flaque** [comment]
THIS IS AMAZING! 

But I would definitely prefer this be in a github action or some other non-test setup. Otherwise, we'll get into a situation where new features can't be added safely without going to every person who's ever translated something :/ 

We should definitely keep track of what's being translated and what's not while still letting us improve and adapt.

**Comment by briankung** [comment]
Sounds good! I’ll look into GitHub Actions next time I get a chance. I’ll close this until then.

**Pull request closed without merging**
