### PR TITLE
class

### PR DESCRIPTION
**Pull request by Faguni786**
request to learn the pull request

### CODE REVIEW

**Comment by Faguni786** [comment]
--

**Comment by lmaoitsrlyme** [comment]
updated app.js

**Comment by joel794** [comment]
hello

**Comment by Faguni786** [comment]
testing

**Comment by Aditya160507** [comment]
complete

**Comment by suhaas30** [comment]
I really like what Quirk is trying to do

**Comment by Mighty2008** [comment]
hi

**Comment by sriyabetageri** [comment]
changed background color to yellow and font size

**Pull request closed without merging**
