### PR TITLE
Add Spanish + German + Polish + Korean + Dutch + Finnish

### PR DESCRIPTION
**Pull request by Flaque**
# Overview

This PR combines #53, #58, #57 and fixes a camel case issue.

Absolutely AMAZING work! Thank you so much! @devinroche @devilcius @kwierbol @idnovic!!!!!

### CODE REVIEW

**Comment by Flaque** [comment]
THIS. IS. AMAZING!

Screen Shot 2019-04-07 at 11 43 06 AM

Simulator Screen Shot - iPhone XS - 2019-04-07 at 11 47 59

Simulator Screen Shot - iPhone XS - 2019-04-07 at 11 53 43

**Comment by idnovic** [comment]
found something,
But this is going to be a hard fix without dictionary
Is it possible to split words with "-"  at the end of an line?
in the german screenshot it should be "Verhaltens-therapie" not "Verhaltenst herapie"

**Comment by idnovic** [comment]
but I think this may be problematic with different screen sizes. So leave it :)

**Comment by Flaque** [comment]
Let me try it out and see what happens 👍

**Comment by idnovic** [comment]
thank you! Already found few things I need to fix. I will wait until I can try these translations on device

**Comment by Flaque** [comment]
> I will wait until I can try these translations on device

Solid, I'm going to ship these out as a first version. That'll let you all play around with it on a real device 🎉

**Comment by briankung** [comment]
Should future translation Pull Requests be made against the `translations` branch or just `master`?

**Comment by Flaque** [comment]
@briankung --> I moved them on to here because I messed up a bit and let some of the `en.json` keys be camelCase while the others were under_score.

So then other folks ended up copying that mistake and I didn't want to ask people to do to much tedium, so I moved all of them into here and then I wrote a script for it:

```bash
#!/bin/bash
sed -i "" "s/crashCourse/crash_course/g" $1
sed -i "" "s/moodThoughts/mood_thoughts/g" $1
sed -i "" "s/thoughtsArentThoughts/thoughts_arent_thoughts/g" $1
sed -i "" "s/yourDistorted/your_distorted/g" $1
sed -i "" "s/cbtOverview/cbt_overview/g" $1
sed -i "" "s/badThoughtNote/bad_thought_note/g" $1
sed -i "" "s/identifyDistortions/identify_distortions/g" $1
sed -i "" "s/badDistortions/bad_distortions/g" $1
sed -i "" "s/challengeScreen/challenge_screen/g" $1
sed -i "" "s/writeChallenge/write_challenge/g" $1
sed -i "" "s/altThought/alt_thought/g" $1
sed -i "" "s/showOff/show_off/g" $1
sed -i "" "s/gotIt/got_it/g" $1
sed -i "" "s/btnTitle/btn_title/g" $1
```

So @briankung if you can run that script against your translations, feel free to make it against master. Otherwise, feel free to make it against this branch and I'll do it :+1:

**Comment by briankung** [comment]
Over on https://github.com/Flaque/quirk/pull/74 I noticed that `thoughts_arent_thoughts.line2` was added in the German translations and not used. Any thoughts on how to handle emphasis in different locations in the sentence in different languages? I read [on another issue](https://github.com/Flaque/quirk/issues/36#issuecomment-468902745) that it's possible to add rich text _within_ the localization string itself instead of outside it. Is that a possibility?

**Comment by Flaque** [comment]
@briankung --> I believe that's only for react on the web, not react native.

But the idea is interesting. Thoughts on Markdown work in other languages?

Like could we do:

```
Bist du dir sicher George hast dich? Wenn nicht, bist du am **Gedanken Lesen** 
Ich war nicht auf Georg's Party, er hasst mich bestimmt.
```

Which we could parse in the app and then spit out React components like:

```jsx
<Text>
Bist du dir sicher George hast dich? Wenn nicht, bist du am 
<Exaggerated>Gedanken Lesen</Exaggerated>
Ich war nicht auf Georg's Party, er hasst mich bestimmt.
</Text>
```

**Comment by devinroche** [comment]
@Flaque This might actually be the best way to do this. It would take a little more logic work but i think its possible.. at least doing something like 
```
let translation = i18n.t('somestring').split('**')
<Text>
    {translation[0]}
    <Emphasis>{translation[1]}</Emphasis>
    {translation[2]}
</Text>
```
^ this probable isnt 100% the solution, but close... thoughts?

**Comment by Flaque** [comment]
@devinroche we can just use remark: https://github.com/remarkjs/remark-react

**Comment by idnovic** [comment]
#german translation: I added iirc 2 new lines at 2 different spots. I did not know that these would end up unused. I can work with markdown. Sounds good.

**Comment by Flaque** [comment]
We should follow up on some of the translation issues in another PR. For the moment, we should merge this so folks are getting at least some translations.

**Pull request merged**
