### PR TITLE
Styling Changed

### PR DESCRIPTION
**Pull request by akshatraajjs**
**Notifications** are improved and **color** changed.

### CODE REVIEW

**Comment by AshutoshSwamy** [comment]
Improve The Notifications System

**Comment by narenMaster** [comment]
i changed the styling

**Comment by WhiteKanavJunior** [comment]
I have changed the styling

**Comment by theInevitable007** [comment]
I have changed the styling. Random

**Comment by saikeerthana-123** [comment]
Added text

**Comment by prathamsatnalika** [comment]
App.js not found

**Pull request closed without merging**
